### PR TITLE
Apply round screen qualifier to device config

### LINKED ISSUE #1029: Resource qualifiers: Round display does not load layout from layout-round
**Description**
When setting `screenRound = ScreenRound.ROUND` in DeviceConfig layouts are not loaded from `layout-round`, but from the default `layout` folder.
This might also be a layoutLib issue, but I was not sure so I decided to report here first.

**Steps to Reproduce**
1. Create a custom view with two XML files in `layout` and `layout-round` that differ
2. Use Paparazzi to take a screenshot of the view

**Expected behavior**
When `screenRound = ScreenRound.ROUND` : The layout from `layout-round` is used
When `screenRound = ScreenRound.NOTROUND`: The layout from `layout` is used

**Additional information:**
Paparazzi Version: 1.2
OS: macOS 13.1 (22C65) aarch64
Compile SDK: 31
Gradle Version: 7.5.1
Android Gradle Plugin Version: 7.4.0

### PR DESCRIPTION
**Pull request by BrianGardnerAtl**
Fixes #1029

### CODE REVIEW

**Review by jrodbx — APPROVED** [review]
nice!

**Comment by jrodbx** [comment]
there seems to be a conflict in `PaparazziPluginTest`, mind resolving?

File: paparazzi-gradle-plugin/src/test/projects/verify-screen-round/src/main/java/app/cash/paparazzi/plugin/test/RoundView.kt [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package app.cash.paparazzi.plugin.test
```
Comment (jrodbx) [inline paparazzi-gradle-plugin/src/test/projects/verify-screen-round/src/main/java/app/cash/paparazzi/plugin/test/RoundView.kt:1]: this can be deleted?

File: paparazzi-gradle-plugin/src/test/projects/verify-screen-round/src/test/java/app/cash/paparazzi/plugin/test/RoundViewTest.kt [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+import com.google.testing.junit.testparameterinjector.TestParameterInjector
+import org.junit.Rule
+import org.junit.Test
+import org.junit.runner.RunWith
+
+@RunWith(TestParameterInjector::class)
+class RoundViewTest(
+  @TestParameter val configuration: ScreenRoundTestConfiguration
+) {
+
```
Comment (jrodbx) [inline paparazzi-gradle-plugin/src/test/projects/verify-screen-round/src/test/java/app/cash/paparazzi/plugin/test/RoundViewTest.kt:16]:
```suggestion
```

File: paparazzi-gradle-plugin/src/test/projects/verify-screen-round/build.gradle [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+  }
+  compileOptions {
+    sourceCompatibility = libs.versions.javaTarget.get()
+    targetCompatibility = libs.versions.javaTarget.get()
+  }
+  kotlinOptions {
+    jvmTarget = libs.versions.javaTarget.get()
+  }
+}
+dependencies {
```
Comment (jrodbx) [inline paparazzi-gradle-plugin/src/test/projects/verify-screen-round/build.gradle:21]:
```suggestion
}

dependencies {
```

**Review by jrodbx — APPROVED** [review]

File: paparazzi-gradle-plugin/src/test/projects/verify-screen-round/src/test/java/app/cash/paparazzi/plugin/test/RoundViewTest.kt [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+  @get:Rule
+  val paparazzi = Paparazzi(
+    deviceConfig = DeviceConfig.GALAXY_WATCH4_CLASSIC_LARGE.copy(screenRound = configuration.round),
+    theme = "android:Theme.Material.Light.NoActionBar"
+  )
+
+  @Test
+  fun textShouldSayRound() {
```
Comment (jrodbx) [inline paparazzi-gradle-plugin/src/test/projects/verify-screen-round/src/test/java/app/cash/paparazzi/plugin/test/RoundViewTest.kt:24]: won't this only apply to one of the test iterations?

**Review by jrodbx — APPROVED** [review]
