### PR TITLE
Skip copying android.os.Build fields for unknown fields

### LINKED ISSUE #794: Build reflection fails with new Build fields: java.lang.NoSuchFieldException UPSIDE_DOWN_CAKE
**Description**
When compiling with an upcoming SDK that doesn't match the version of `layoutlib`, where `android.os.Build` has additional fields that are not in the `android.os._Original_Build` in `layoutlib`, attempting to fetch the values from `android.os._Original_Build` reflectively will result in a `NoSuchFieldException` in cases where it is a new field that doesn't exist yet in `android.os._Original_Build` (such as `Build.VERSION_CODES.UPSIDE_DOWN_CAKE`.

**Steps to Reproduce**

- Update sample compile sdk to be `compileSdkPreview "UpsideDownCake"`:
  https://github.com/cashapp/paparazzi/blob/4a053b6dd963dbacb049c47c1cbfbb8aac27adb3/sample/build.gradle#L8
- Run `./gradlew :sample:recordPaparazziDebug`
- Failure, with the stacktrace from the first test of 

  ```
  java.lang.NoSuchFieldException: UPSIDE_DOWN_CAKE
  	at java.base/java.lang.Class.getField(Class.java:2117)
  	at app.cash.paparazzi.internal.Renderer.configureBuildProperties(Renderer.kt:159)
  	at app.cash.paparazzi.internal.Renderer.prepare(Renderer.kt:118)
  	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:157)
  	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:123)
  	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
  ```

**Expected behavior**
`./gradlew :sample:recordPaparazziDebug` to succeed.

**Additional information:**
- Paparazzi Version: 1.3.0-SNAPSHOT @ https://github.com/cashapp/paparazzi/commit/4a053b6dd963dbacb049c47c1cbfbb8aac27adb3
- OS: Linux
- Compile SDK: "UpsideDownCake"
- Gradle Version: 7.6
- Android Gradle Plugin Version: 7.4.2

### PR DESCRIPTION
**Pull request by alexvanyo**
Updates the `android.os.Build` copying logic via reflection to gracefully ignore fields that exist in `android.os.Build` but don't exist in `android.os._Original_Build`. These are likely new fields, which will be introduced with new compile sdk versions.

This fixes #794.

### CODE REVIEW

File: paparazzi/paparazzi-gradle-plugin/src/test/projects/build-class-next-sdk/src/test/java/app/cash/paparazzi/plugin/test/BuildClassTest.kt [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+ * limitations under the License.
+ */
+package app.cash.paparazzi.plugin.test
+
+import android.os.Build
+import app.cash.paparazzi.Paparazzi
+import org.junit.Rule
+import org.junit.Test
+
+class BuildClassTest {
```
Comment (alexvanyo) [inline paparazzi/paparazzi-gradle-plugin/src/test/projects/build-class-next-sdk/src/test/java/app/cash/paparazzi/plugin/test/BuildClassTest.kt:23]: This is a copy of the existing `build-class` test project, with the values below adjusted to match the current platform of `android-UpsideDownCake`.

File: paparazzi/paparazzi-gradle-plugin/src/test/java/app/cash/paparazzi/gradle/PaparazziPluginTest.kt [hunk 2]
```diff
@@ -191,6 +191,18 @@ class PaparazziPluginTest {
     assertThat(snapshotsDir.exists()).isFalse()
   }
 
+  @Test
+  fun buildClassNextSdkAccess() {
+    val fixtureRoot = File("src/test/projects/build-class-next-sdk")
```
Comment (alexvanyo) [inline paparazzi/paparazzi-gradle-plugin/src/test/java/app/cash/paparazzi/gradle/PaparazziPluginTest.kt:196]: Happy to take alternate suggestions for the naming of `build-class-next-sdk` that will be the most clear for future maintenance.

**Review by jrodbx — APPROVED** [review]
nice.  thanks!
