### PR TITLE
Fixes crash when using InputMethodManager to show/hide keyboard.

### LINKED ISSUE #407: Bumblebee Layoutlib doesn't stub out InputMethodManager properly
The Bumblebee version of layoutlib now returns an InputMethodManager via getSystemService when requested.
While layoutlib does attempt to stub it out, it unfortunately doesn't do so correctly:

Example stack trace:
```
INFO: imeTracing [4]: Exception while creating ImeTracing instance
android.os.ServiceManager$ServiceNotFoundException: No service published for: input_method
at android.os.ServiceManager.getServiceOrThrow(ServiceManager.java:37)
at android.util.imetracing.ImeTracing.(ImeTracing.java:61)
at android.util.imetracing.ImeTracingClientImpl.(ImeTracingClientImpl.java:33)
at android.util.imetracing.ImeTracing.getInstance(ImeTracing.java:75)
at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1746)
at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1740)
at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1709)
at com.squareup.util.android.Keyboards.hideKeyboard(Keyboards.kt:23)
at com.squareup.util.android.Keyboards.hideKeyboard(Keyboards.kt:13)
at com.squareup.cash.mooncake.components.AlertDialogView.onAttachedToWindow(AlertDialogView.kt:75)
```

While method interception or an upstream fix is likely the long-term solution, for now, our internal workaround is to avoid it in tests so:

```
open class AlertDialogView @JvmOverloads constructor(
  context: Context,
  attrs: AttributeSet? = null,
  private val hideKeyboard: Boolean = true
) : FrameLayout(context, attrs) {

  ...

  override fun onAttachedToWindow() {
    super.onAttachedToWindow()

    if (hideKeyboard) {
      val inputMethodManager = context.getSystemService(InputMethodManager::class.java)
      inputMethodManager.hideSoftInputFromWindow(this.windowToken, 0)
    }
  }
```

and passing `hideKeyboard = false` in the paparazzi test.

### PR DESCRIPTION
**Pull request by luis-cortes**
Fixes #407 

This fix requires two changes.

First, we prevent layoutlib's version of ServiceManager from throwing a ServiceNotFoundException when
it's asked to find the "input_method" service.

Second, we return the default implementation for IInputMethodManager in IInputMethodManager.Stub.asInterface.
This ensures that the mService field in ImeTracing is not null.

### CODE REVIEW

File: paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt [hunk 1]
```diff
@@ -506,6 +510,20 @@ class Paparazzi @JvmOverloads constructor(
...
   }
 
+  private fun registerServiceManagerInterception() {
+    val serviceManager = Class.forName("android.os.ServiceManager")
+    InterceptorRegistrar.addMethodInterceptor(
+      serviceManager, "getServiceOrThrow", ServiceManagerInterceptor::class.java
+    )
+  }
+
+  private fun registerImmInterception() {
```
Comment (jrodbx) [inline paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt:520]:
```suggestion
  private fun registerInputMethodManagerInterception() {
```

**Review by jrodbx — APPROVED** [review]
Please update the commit title to something relevant, e.g., "Fix crash on InputMethodManager keyboard operations" or similar.
