### PR TITLE
use Google's published layoutlib

### LINKED ISSUE #717: layoutlib module clones "the world"
As a contributor I wanted to quickly test something in relation to a PR in this repo.
I ran `gradlew publishToMavenLocal` and that started `cloneLayoutLib`, which took 1.5 hours, only to end with:
```
* What went wrong:
Execution failed for task ':libs:layoutlib:cloneLayoutlib'.
> There is not enough space on the disk
```

I double-checked and the `paparazzi\build\prebuilts\studio\layoutlib\.git` folder is 10G. Is it really necessary to pull everything from the server to only get the 300M of `paparazzi\build\prebuilts\studio\layoutlib\data` we need?

_After writing this report I realized that I should've been more specific about which module I want to pubish..._ the issue still stands, we could achieve a 97% bandwidth and disk space saving. 😅

### Investigation

Out of curiosity how hard this is, I did the following:
```shell
$ git clone https://android.googlesource.com/platform/prebuilts/studio/layoutlib . --depth=1 --single-branch
Cloning into '.'...
remote: Finding sources: 100% (2/2)
remote: Total 2 (delta 0), reused 2 (delta 0)
Receiving objects: 100% (2/2), done.

$ git status
On branch master
Your branch is up to date with 'origin/master'.

$ git fetch origin f5f9f71
fatal: couldn't find remote ref f5f9f71

$ git fetch origin studio-2022.1.1-beta4 --depth 1
remote: Finding sources: 100% (10480/10480)
Receiving objects: 100% (10480/10480), 181.67 MiB | 348.00 KiB/s, done.

Resolving deltas: 100% (2160/2160), done.
From https://android.googlesource.com/platform/prebuilts/studio/layoutlib
 * tag               studio-2022.1.1-beta4 -> FETCH_HEAD
```

That said, this (ab)uses the fact that the repo's `master` just happens to be empty, I tried again and this one command does it all:
```shell
$ git clone https://android.googlesource.com/platform/prebuilts/studio/layoutlib --branch studio-2022.1.1-beta4 --single-branch --depth 1 .
Cloning into '.'...
remote: Finding sources: 100% (10484/10484)
Receiving objects: 100% (10484/10484), 181.67 MiB | 344.00 KiB/s, done.

Resolving deltas: 100% (2160/2160), done.
Note: switching to 'f5f9f71ebf7658a26af18684242501e987968ddb'.

Updating files: 100% (10647/10647), done.
```

### LINKED ISSUE #1221: Bump Layoutlib to Jellyfish and migrate to Google's published artifacts
See:
- https://maven.google.com/web/index.html?q=layoutlib#com.android.tools.layoutlib:layoutlib
- https://maven.google.com/web/index.html?q=layoutlib#com.android.tools.layoutlib:layoutlib-runtime
- https://issuetracker.google.com/issues/241795063

Per @JoseAlcerreca, version 14.0.1 is the version used in Jellyfish canaries.

### PR DESCRIPTION
**Pull request by gabrielittner**
Closes #1221.
Closes #884.
Closes #717.

- Replaces the manually published layoutlib modules with the new artifacts published by Google.
- In 14.0.3 a new `layoutlib-resources` artifact was introduced. This contains the icu, keyboard and font files that previously were in the main layoutlib artifacts. It also contains a `res` folder which can be used instead of reading resources from the SDK platform directory.
- In 14.0.4 icu, keyboard and font files moved back to the main layoutlib artifacts. `layoutlib-resources` now only contains the `res` folder which moved to a top level directory inside the jar.
- ~Initially I've also upgraded `layoutlib-api` to the Jellyfish preview versions. However it's not actually needed for everything to work, so I downgraded it again. Because of that this PR does not depend on any alpha/beta versions, but I guess the `14.0.x` layoutlib artifacts could still be considered as not stable until AS Jellyfish is stable.~

### CODE REVIEW

File: paparazzi/src/main/java/app/cash/paparazzi/internal/resources/base/BasicResourceItem.kt [hunk 1]
```diff
@@ -91,8 +91,6 @@ abstract class BasicResourceItem(
     }
   }
 
-  override fun setValue(value: String?): Unit = throw UnsupportedOperationException()
```
Comment (gabrielittner) [inline paparazzi/src/main/java/app/cash/paparazzi/internal/resources/base/BasicResourceItem.kt:94]: Method was removed from the base class/interface

File: paparazzi/src/main/java/app/cash/paparazzi/internal/Renderer.kt [hunk 2]
```diff
@@ -114,7 +114,7 @@ internal class Renderer(
     val platformDataDir = File(platformDataRoot, "data")
     val fontLocation = File(platformDataDir, "fonts")
     val nativeLibLocation = File(platformDataDir, getNativeLibDir())
-    val icuLocation = File(platformDataDir, "icu" + File.separator + "icudt70l.dat")
+    val icuLocation = File(platformDataDir, "icu" + File.separator + "icudt72l.dat")
```
Comment (gabrielittner) [inline paparazzi/src/main/java/app/cash/paparazzi/internal/Renderer.kt:117]: File name changed in the new layoutlib version

File: paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt [hunk 3]
```diff
@@ -616,7 +607,7 @@ class Paparazzi @JvmOverloads constructor(
     synchronized(this) {
       // https://android.googlesource.com/platform/frameworks/layoutlib/+/d58aa4703369e109b24419548f38b422d5a44738/bridge/src/com/android/layoutlib/bridge/BridgeRenderSession.java#171
       // BridgeRenderSession.executeCallbacks aggressively tears down the main Looper and BridgeContext, so we call the static delegates ourselves.
-      Handler_Delegate.executeCallbacks()
+      Handler_Delegate.executeCallbacks(System_Delegate.nanoTime())
```
Comment (gabrielittner) [inline paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt:610]: This is effectifely what `executeCallbacks` used to do internally before, but now it requires the time to be passed in

File: paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt [hunk 4]
```diff
@@ -352,29 +353,19 @@ class Paparazzi @JvmOverloads constructor(
...
     // Execute the block at the requested time.
     System_Delegate.setNanosTime(frameNanos)
 
-    val choreographer = Choreographer.getInstance()
-    val areCallbacksRunningField = choreographer::class.java.getDeclaredField("mCallbacksRunning")
-    areCallbacksRunningField.isAccessible = true
+    // should happen before doCallbacks so that compose re-composition happens
+    executeHandlerCallbacks()
+    // 1 is the only callbackType allowed by doCallbacks
+    Choreographer_Delegate.doCallbacks(Choreographer.getInstance(), 1, frameNanos)
```
Comment (gabrielittner) [inline paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt:366]: `Choreographer_Delegate` also has a `doFrame` method that updates the choreographer time and runs the callbacks. But I decided against using it for now because `sChoreographerTime` is only updated after the callbacks run which would require changing some tests that rely on the time to be already updated and I wanted to avoid updating the tests for now. It also a bit more complicated to use because `sChoreographerTime` can apparently not become smaller without breaking things (`PaparazziTest.animationCallbacksForStaticSnapshots` was suceeding when run on its own but failed when running all of `PaparazziTest` when I tried using doFrame and starting with `0` in each test).

File: paparazzi/src/main/java/app/cash/paparazzi/DeviceConfig.kt [hunk 5]
```diff
@@ -261,7 +261,7 @@ data class DeviceConfig(
       xdpi = 440,
       ydpi = 440,
       orientation = ScreenOrientation.PORTRAIT,
-      density = Density.DPI_420,
+      density = Density.create(420),
```
Comment (gabrielittner) [inline paparazzi/src/main/java/app/cash/paparazzi/DeviceConfig.kt:264]: Density was changed from an enum to a class.

Comment (TWiStErRob) [reply paparazzi/src/main/java/app/cash/paparazzi/DeviceConfig.kt:264]: Hmm, someone was asking for something like this.

File: gradle/libs.versions.toml [hunk 6]
```diff
@@ -11,11 +11,9 @@ ktlint = "0.50.0"
 moshi = "1.15.0"
 
 minSdk = "25"
-compileSdk = "33"
+compileSdk = "34"
 
-# Maps to this commit: https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/5e972ea
-layoutlib = "2022.3.1-5e972ea"
-layoutlibPrebuiltSha = "5e972ea"
+layoutlib = "14.0.1"
```
Comment (TWiStErRob) [inline gradle/libs.versions.toml:16]: How much of this PR is actually part of #1216 and #1220?

Comment (gabrielittner) [reply gradle/libs.versions.toml:16]: The compileSdkVersion bump can and probably needs to already happen with the Iguana update. As for the API changes, I'd need to try building it to find out.

File: paparazzi/src/main/java/app/cash/paparazzi/internal/resources/base/BasicFileResourceItem.kt [hunk 7]
```diff
@@ -86,7 +86,7 @@ open class BasicFileResourceItem(
       if (encodedDensity == 0) {
         return BasicFileResourceItem(resourceType, name, configuration, visibility, relativePath)
       }
-      val density = Density.values()[encodedDensity - 1]
+      val density = Density.create(encodedDensity)
```
Comment (gabrielittner) [inline paparazzi/src/main/java/app/cash/paparazzi/internal/resources/base/BasicFileResourceItem.kt:89]: https://cs.android.com/android-studio/platform/tools/base/+/a728d0c33ce30df27187501c61fdbe6e760342af:resource-repository/main/java/com/android/resources/base/BasicFileResourceItem.java;dlc=471934f339e1ccc75ab79d8def98ff876f1eb75f

File: gradle/libs.versions.toml (hunk 6 above)
Comment (gabrielittner) [reply gradle/libs.versions.toml]: I've rebased this PR and restructured the commits. The first commit bumps the version to Iguana 2023.2.1-beta02-6c7316c, the following commits then apply the required changes for Iguana and the last commit bumps to Jellyfish and Google's artifacts. All the changes here except for that last commit are already needed to make the Iguana layoutlib run.

Iguana has the same issue with the 3 tests that are failing on either macOS or on Windows+Linux, depending on where the snapshot was created. I made a test run with a manually published 2023.2.1-beta02-6c7316c here https://github.com/freeletics/paparazzi/actions/runs/7590152036

File: .github/workflows/build.yml [hunk 8]
```diff
@@ -18,7 +18,7 @@ jobs:
       fail-fast: false
       matrix:
         os: [
-          macOS-latest,
+          macos-14,
```
Comment (gabrielittner) [inline .github/workflows/build.yml:21]: This uses the newer ARM based macOS runner and makes `composeA11y`, `customFontsInCode`, and `customFontsInXml`. The 3 tests would still fail on Intel macOS, it seems that that variant of layoutlib has a small but bigh enough rendering difference compared to macOS ARM, Linux and Windows. 

I've also did a test with the latest tagged Iguana layoutlib by publishing it myself and with the same changes as this PR (except for the last commit [3b2c9c4](https://github.com/cashapp/paparazzi/pull/1228/commits/3b2c9c4da4d28cd172a796991f9c3d2152513d13)) Iguana also works: https://github.com/freeletics/paparazzi/actions/runs/7731866563

File: paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt [hunk 9]
```diff
@@ -76,6 +76,7 @@ public class PaparazziPlugin : Plugin<Project> {
   private fun <T> setupPaparazzi(project: Project, variants: DomainObjectSet<T>) where T : BaseVariant, T : TestedVariant {
     project.addTestDependency()
     val nativePlatformFileCollection = project.setupNativePlatformDependency()
+    val layoutlibResourcesFileCollection = project.setupLayoutlibResourcesDependency()
```
Comment (gabrielittner) [inline paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt:79]: Everything except for the native lib itself moved to a new `layoutlib-resources` artifact in 14.0.3, so we need to unzip that one as well and have 2 system properties for passing the directories to the test

**Comment by gabrielittner** [comment]
With the Iguana update merged I've rebased this and updated the PR description. Other than the new `layoutlib-resources` artifact that reduces the reliance on the local Android SDK directory there seems to be no required change to the Paparazzi code from this update.

File: gradle/libs.versions.toml [hunk 10]
```diff
@@ -14,9 +14,8 @@ moshi = "1.15.1"
 minSdk = "25"
 compileSdk = "34"
 
-# Maps to this commit: https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/6c7316c
-layoutlib = "2023.2.1-6c7316c"
-layoutlibPrebuiltSha = "6c7316c"
+layoutlibApi = "31.3.1"
```
Comment (TWiStErRob) [inline gradle/libs.versions.toml:17]: Should this be replaced with versions.androidTools instead?

File: libs/layoutlib/build.gradle [hunk 11]
```diff
@@ -1,61 +0,0 @@
-import org.ajoberstar.grgit.Grgit
```
Comment (TWiStErRob) [inline libs/layoutlib/build.gradle:1]: Only used here, there are traces of it left in toml and build-logic.

Also "closes #884"

File: gradle/libs.versions.toml (hunk 10 above)
Comment (gabrielittner) [reply gradle/libs.versions.toml:17]: I've kept it separate like before because there might still be situations in the future where this might need to be updated independently.

File: libs/layoutlib/build.gradle (hunk 11 above)
Comment (gabrielittner) [reply libs/layoutlib/build.gradle:1]: Removed the leftovers 👍 [e62b010](https://github.com/cashapp/paparazzi/pull/1228/commits/e62b010f7a167a8d923f259a3b89fbcccfac35e6)

Comment (TWiStErRob) [reply libs/layoutlib/build.gradle:1]: Nice, also just realised, transitively "fixes #717"

**Comment by gabrielittner** [comment]
I've updated the PR to layoutlib-api 31.4.0 and layoutlib 14.0.7 which should match the stable Jellyfish release.

The last commit updates screenshots for the following 4 tests, in all of them the compose font padding changes. I believe there might be a build cache issue that causes them not to fail on master because compose 1.6.0 changed the default font padding and the last commit on master bumped compose from 1.5.x to 1.6.x. In this pr the 4 tests started failing after just merging master into this branch.
```
PaparazziPluginTest.compose
PaparazziPluginTest.composeA11y
PaparazziPluginTest.composeWear
PaparazziPluginTest.nightModeCompose
```

**Comment by gabrielittner** [comment]
@jrodbx With 1.3.4 out, can this get merged? Happy to make any additional changes if needed but all tests are succeeding without any changes to them

File: gradle/libs.versions.toml [hunk 12]
```diff
@@ -13,9 +13,8 @@ moshi = "1.15.1"
 minSdk = "25"
 compileSdk = "34"
 
-# Maps to this commit: https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/6c7316c
-layoutlib = "2023.2.1-6c7316c"
-layoutlibPrebuiltSha = "6c7316c"
+layoutlibApi = "31.4.1"
```
Comment (jrodbx) [inline gradle/libs.versions.toml:16]: inline, since only one use

File: gradle/libs.versions.toml [hunk 13]
```diff
@@ -13,9 +13,8 @@ moshi = "1.15.1"
...
+layoutlib = "14.0.8"
```
Comment (jrodbx) [inline gradle/libs.versions.toml:17]: move up to line 11, since it's now just another "normal" version

File: gradle/libs.versions.toml [hunk 14]
```diff
@@ -57,7 +50,10 @@ moshi-kotlinReflect = { module = "com.squareup.moshi:moshi-kotlin", version.ref
 okio = { module = "com.squareup.okio:okio", version = "3.9.0" }
 
 tools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
-tools-layoutlib = { module = "com.android.tools.layoutlib:layoutlib-api", version = "31.4.1" }
+tools-layoutlib-api = { module = "com.android.tools.layoutlib:layoutlib-api", version.ref = "layoutlibApi" }
+tools-layoutlib = { module = "com.android.tools.layoutlib:layoutlib", version.ref = "layoutlib" }
```
Comment (jrodbx) [inline gradle/libs.versions.toml:54]: nit: ordering, move this one line up (above api)

File: gradle/libs.versions.toml [hunk 15]
```diff
@@ -57,7 +50,10 @@ moshi-kotlinReflect = { module = "com.squareup.moshi:moshi-kotlin", version.ref
...
+tools-layoutlib-runtime = { module = "com.android.tools.layoutlib:layoutlib-runtime", version.ref = "layoutlib" }
+tools-layoutlib-resources = { module = "com.android.tools.layoutlib:layoutlib-resources", version.ref = "layoutlib" }
```
Comment (jrodbx) [inline gradle/libs.versions.toml:56]: nit: ordering, move this one line up (above runtime)

**Review by jrodbx — APPROVED** [review]
nice work!

**Comment by jrodbx** [comment]
actually, i'll just merge this in now, and address nits in a followup.

**Comment by yogurtearl** [comment]
Swapping transitive deps might warrant a bigger version bump? i.e. `1.4.0` rather than `1.3.5`?
