### PR TITLE
Generate resource ids for aapt inline resources

### LINKED ISSUE #456: NPE on res.getXml()
**Description**

I have a composable with 

```kotlin
val animatedImage = AnimatedImageVector.animatedVectorResource(R.drawable.avd_check)
```

A simple testing with

```kotlin
paparazzi.snapshot { MyComposable() }
```

causes a unit test crash:

```
    java.lang.NullPointerException: res.getXml(resId) must not be null
        at androidx.compose.animation.graphics.res.AnimatorResources_androidKt.loadAnimatorResource(AnimatorResources.android.kt:52)
        at androidx.compose.animation.graphics.vector.compat.XmlAnimatedVectorParser_androidKt.parseAnimatedVectorTarget(XmlAnimatedVectorParser.android.kt:44)
        at androidx.compose.animation.graphics.vector.compat.XmlAnimatedVectorParser_androidKt.parseAnimatedImageVector(XmlAnimatedVectorParser.android.kt:70)
        at androidx.compose.animation.graphics.res.AnimatedVectorResources_androidKt.loadAnimatedVectorResource(AnimatedVectorResources.android.kt:61)
        at androidx.compose.animation.graphics.res.AnimatedVectorResources_androidKt.animatedVectorResource(AnimatedVectorResources.android.kt:48)
        at kiwi.orbit.compose.ui.controls.CheckboxKt.Checkbox(Checkbox.kt:109)
```

**Steps to Reproduce**

```kotlin
paparazzi.snapshot { AnimatedImageVector.animatedVectorResource(R.drawable.avd_check) }
```

**Expected behavior**
No crash

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: Windows
- Compile SDK: 32
- Gradle Version: 7.4.1
- Android Gradle Plugin Version: 7.2.0

### LINKED ISSUE #469: NullPointerException when referencing AAPT inlined resources in Compose via `Resources.getXml(id)`
**Description**
AAPT inlined resources are not resolved when referenced from Compose. Due to the way Compose Vector parser works with resources, it first requests an id for resource reference.  But as there is no id for this reference, it falls back to 0, so the resource can't be resolved.

**Stacktrace**
```java
INFO: ComplexColorCompat [4]: Failed to inflate ComplexColor.
java.lang.NullPointerException
	at androidx.core.content.res.ComplexColorCompat.createFromXml(ComplexColorCompat.java:155)
	at androidx.core.content.res.ComplexColorCompat.inflate(ComplexColorCompat.java:140)
	at androidx.core.content.res.TypedArrayUtils.getNamedComplexColor(TypedArrayUtils.java:150)
	at androidx.compose.ui.graphics.vector.compat.AndroidVectorParser.getNamedComplexColor(XmlVectorParser.android.kt:663)
	at androidx.compose.ui.graphics.vector.compat.XmlVectorParser_androidKt.parsePath(XmlVectorParser.android.kt:281)
	at androidx.compose.ui.graphics.vector.compat.XmlVectorParser_androidKt.parseCurrentVectorNode(XmlVectorParser.android.kt:101)
	at androidx.compose.ui.res.VectorResources_androidKt.loadVectorResourceInner(VectorResources.android.kt:81)
	at androidx.compose.ui.res.PainterResources_androidKt.loadVectorResource(PainterResources.android.kt:95)
	at androidx.compose.ui.res.PainterResources_androidKt.painterResource(PainterResources.android.kt:65)
	at co.cuvva.features.cue.presentation.ui.UndeclaredIncidentsUiKt.Header(UndeclaredIncidentsUi.kt:285)
	at co.cuvva.features.cue.presentation.ui.UndeclaredIncidentsUiKt.access$Header(UndeclaredIncidentsUi.kt:1)
	at co.cuvva.features.cue.presentation.ui.UndeclaredIncidentsUiKt$ContentUi$1$1.invoke(UndeclaredIncidentsUi.kt:164)
	at co.cuvva.features.cue.presentation.ui.UndeclaredIncidentsUiKt$ContentUi$1$1.invoke(UndeclaredIncidentsUi.kt:163)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.foundation.lazy.list.LazyListScopeImpl$item$2$1.invoke(LazyListScopeImpl.kt:51)
	at androidx.compose.foundation.lazy.list.LazyListScopeImpl$item$2$1.invoke(LazyListScopeImpl.kt:51)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$content$1.invoke(LazyLayoutItemContentFactory.kt:103)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$content$1.invoke(LazyLayoutItemContentFactory.kt:94)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:251)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:251)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3337)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2582)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2522)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:478)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:748)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2987)
Jun 24, 2022 12:30:33 PM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
```
**Steps to Reproduce**
1. Create a composable that uses a vector drawable with aapt attr inlined resources (like [this one](https://github.com/cashapp/paparazzi/blob/master/paparazzi-gradle-plugin/src/test/projects/verify-aapt-code/src/main/res/drawable/card_chip.xml));
2. Create a simple Paparazzi test and run it;

**Expected behavior**
Inlined resources (like gradients) are supported and rendered correctly in Compose.

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: macOS 12.4
- Compile SDK: 31
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.2.1

**Screenshots**

| Expected screenshot | Actual screenshot |
| - | - |
| image | image |

### PR DESCRIPTION
**Pull request by dniHze**
### About
Compose vector parser first [requests](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/content/res/TypedArrayUtils.java;l=151?q=androidx.core.content.res.TypedArrayUtils.getNamedComplexColor) the id of a resource reference. Then, it is used to [request](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/content/res/ComplexColorCompat.java;l=152?q=ComplexColorCompat%20createFromXml) XML parser and create `ComplexColorCompat` from it. In order to add support for this scheme, IDs should be generated for inlined AAPT attributes, and they should be referencable by this id.

### Changes
* Generate resource ids for aapt inline resources;

### Tests
* Adds `verify-aapt-compose` Gradle test project to verify that vector is rendered correctly;

**Screenshots**
| Before | After |
| - | - |
| image | image |

Also tested locally on a side project. 

Resolves #469.  Closes #456.

### CODE REVIEW

**Comment by dniHze** [comment]
Didn't check this particular case, but this PR may also resolve #456.

**Comment by dniHze** [comment]
👋 @jrodbx, may I ask for your review here?

File: paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt [hunk 1]
```diff
@@ -122,7 +126,14 @@ internal class PaparazziCallback(
       return LayoutPullParser.createFromFile(File(layoutResource.value))
         .also {
           // For parser of elements included in this parser, publish any aapt declared values
-          aaptDeclaredResources.putAll(it.getAaptDeclaredAttrs())
+          it.getAaptDeclaredAttrs()
+            .also(aaptDeclaredResources::putAll)
+            .onEach { (name) ->
+              val id = --aaptResourceId
```
Comment (gamepro65) [inline paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt:132]: Looking at the Android Studio source they generate aapt resource id's within a [specific range](https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:android/src/com/android/tools/idea/res/ResourceIdManager.kt;l=100-117) to prevent collisions and also not until `getOrGenerateResourceId` is called since not all ResourceReference's need a resource id. Can we move this to be inserted on demand in our `getOrGenerateResourceId` function?

Comment (dniHze) [reply paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt]: Thanks for the reference and explanation. Replaced it with `DynamicResourceIdManager` in 
961d304429f10c5d45bb1df0810b8fd8840232a0

File: paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt [hunk 2]
```diff
@@ -122,7 +125,8 @@ internal class PaparazziCallback(
       return LayoutPullParser.createFromFile(File(layoutResource.value))
         .also {
           // For parser of elements included in this parser, publish any aapt declared values
-          aaptDeclaredResources.putAll(it.getAaptDeclaredAttrs())
```
Comment (gamepro65) [inline paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt:125]: nit: Unnecessary change

File: paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt [hunk 3]
```diff
@@ -99,16 +99,19 @@ internal class PaparazziCallback(
...
 
   override fun getOrGenerateResourceId(resource: ResourceReference): Int {
     // Workaround: We load our resource map from fields in R.class, which are named using Java
     // class conventions.  Therefore, we need to similarly transform style naming conventions
     // that contain periods (e.g., Widget.AppCompat.TextView) to avoid false lookup misses.
     // Long-term: Perhaps parse and load resource names from file system directly?
-    val resourceKey =
-      if (resource.resourceType == STYLE) resource.transformStyleResource() else resource
-    return resources[resourceKey] ?: 0
+    val resourceKey = when (resource.resourceType) {
```
Comment (gamepro65) [inline paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt:110]: nit: Since we are only checking one type I think we should leave it as the if statement

**Review by gamepro65 — APPROVED** [review]
Few minor nits but looks good overall

File: paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt (hunk 2 above)
Comment (dniHze) [reply paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt]: reverted here: eb5cbccaded390d4f2ab20b37920b1fd36ca4614

File: paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt (hunk 3 above)
Comment (dniHze) [reply paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/PaparazziCallback.kt]: reverted here: eb5cbccaded390d4f2ab20b37920b1fd36ca4614

**Review by jrodbx — APPROVED** [review]
Nice!  Mind rebasing to latest?

File: paparazzi/paparazzi-gradle-plugin/src/test/projects/verify-aapt-compose/build.gradle [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+android {
+  compileSdkVersion 31
+  defaultConfig {
+    minSdkVersion 25
+  }
+  buildFeatures {
+    compose true
+  }
+  composeOptions {
+    kotlinCompilerExtensionVersion '1.1.1'
```
Comment (jrodbx) [inline paparazzi/paparazzi-gradle-plugin/src/test/projects/verify-aapt-compose/build.gradle:25]:
```suggestion
    kotlinCompilerExtensionVersion '1.3.0'
```

File: paparazzi/paparazzi-gradle-plugin/src/test/projects/verify-aapt-compose/build.gradle [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+  }
+}
+
+dependencies {
+  implementation 'androidx.compose.material:material:1.1.1'
```
Comment (jrodbx) [inline paparazzi/paparazzi-gradle-plugin/src/test/projects/verify-aapt-compose/build.gradle:30]:
```suggestion
  implementation 'androidx.compose.material:material:1.2.1'
```

**Review by jrodbx — APPROVED** [review]
