### PR TITLE
Override andorid.os.Build class fields to android.os_Original_Build

### LINKED ISSUE #380: Null Pointer When Using Material TextInputEditText
When using `com.google.android.material.textfield.TextInputEditText`

It looks like the following line is throwing an error...

```
    public static boolean isMeizuDevice() {
        return Build.MANUFACTURER.toLowerCase(Locale.ENGLISH).equals("meizu");
    }
```

```
java.lang.NullPointerException
	at com.google.android.material.internal.ManufacturerUtils.isMeizuDevice(ManufacturerUtils.java:36)
	at com.google.android.material.textfield.TextInputEditText.onAttachedToWindow(TextInputEditText.java:90)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5278)
	at android.view.ViewGroup.addView(ViewGroup.java:5064)
	at android.view.ViewGroup.addView(ViewGroup.java:5004)
	at android.view.ViewGroup.addView(ViewGroup.java:4976)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:255)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:176)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:169)
	at org.sharethemeal.android.view.settings.SettingsScreenShotTest.editProfileFragment(SettingsScreenShotTest.kt:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:108)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:420)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

### PR DESCRIPTION
**Pull request by geoff-powell**
fixes #380, #758, #631

Currently using reflection to map these classes. As @JerryLocke [points out, LayoutLib is using a class loader](https://github.com/cashapp/paparazzi/issues/91#issuecomment-545724167) to swap `_Original_Build` for `Build` since the `SystemProperties` are loaded from `Bridge.init()` and static fields of `Build` are configured at application start. 

The final solution _should_ involve [using a custom class loader like AndroidStudio](https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:layoutlib/src/com/android/layoutlib/LayoutlibClassLoader.java;bpv=0) uses or class replacement via bytecode manipulation with [ByteBuddy](https://bytebuddy.net/#/) or direct [Java ASM work](https://asm.ow2.io/).

The added test here mainly verifies issue #380 where Material TextInputLayout couldn't be used since it does a `Build.*` check when attached to the window.

### CODE REVIEW

File: paparazzi/paparazzi-gradle-plugin/src/test/java/app/cash/paparazzi/gradle/PaparazziPluginTest.kt [hunk 1]
```diff
@@ -915,10 +913,14 @@ class PaparazziPluginTest {
 
     val snapshotsDir = File(fixtureRoot, "build/reports/paparazzi/images")
     val snapshots = snapshotsDir.listFiles()
-    assertThat(snapshots!!).hasLength(1)
+    assertThat(snapshots!!).hasLength(2)
```
Comment (TWiStErRob) [inline paparazzi/paparazzi-gradle-plugin/src/test/java/app/cash/paparazzi/gradle/PaparazziPluginTest.kt:916]: Careful here, [`.listFiles` JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#listFiles--):

> There is no guarantee that the name strings in the resulting array will appear in any specific order; they are not, in particular, guaranteed to appear in alphabetical order.

Based on the above, think this could result in a flaky test.

Other places in this file apply `?.sortedBy { it.lastModified() }` when there's more than one file.

File: paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/Renderer.kt [hunk 2]
```diff
@@ -100,6 +103,7 @@ internal class Renderer(
           logger
         )
       ) { "Failed to init Bridge." }
+      configureAndroidOSBuild()
     }
```
Comment (jrodbx) [inline paparazzi/paparazzi/src/main/java/app/cash/paparazzi/internal/Renderer.kt:107]:
```suggestion
    }
    configureBuildProperties()
```

File: gradle/libs.versions.toml [hunk 3]
```diff
@@ -45,6 +45,8 @@ layoutlib-native-macArm = { module = "app.cash.paparazzi:layoutlib-native-macarm
 layoutlib-native-macOsX = { module = "app.cash.paparazzi:layoutlib-native-macosx", version.ref = "layoutlib" }
 layoutlib-native-windows = { module = "app.cash.paparazzi:layoutlib-native-win", version.ref = "layoutlib" }
 
+material = { group = "com.google.android.material", name = "material", version = "1.8.0" }
```
Comment (jrodbx) [inline gradle/libs.versions.toml:48]: while #380 is definitely a recent example of this bug, I think the issue ultimately is that Build.FOO references weren't working, so I'd like to suggest:

1) reverting these test changes
2) adding a plugin test that is something like this:

```
class BuildTest {
  @get:Rule
  val paparazzi = Paparazzi()

  @Test
  fun build() {
    assertThat(Build.SOME_VALUE).isEqualTo("whatevs")
    // ... pick a few values per known issues
  }
}
```

**Review by jrodbx — APPROVED** [review]
awesome!  this won't fix/patch method calls like:
```
    public static String getSerial()
    public static String getRadioVersion()
    public static void ensureFingerprintProperty()
    public static String getFingerprintedPartitions()
```
but I think that's OK for now!  Eventually, would be nice to swap to using a custom ClassLoader like Android Studio does.

File: paparazzi/paparazzi-gradle-plugin/src/test/projects/build-class/src/test/java/app/cash/paparazzi/plugin/test/BuildClassTest.kt [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+import org.junit.Test
+
+class BuildClassTest {
+  @get:Rule
+  val paparazzi = Paparazzi()
+
+  @Test
+  fun verifyFields() {
+    println(Build.MODEL)
+    assert(Build.ID == "TPB4.220624.004")
```
Comment (TWiStErRob) [inline paparazzi/paparazzi-gradle-plugin/src/test/projects/build-class/src/test/java/app/cash/paparazzi/plugin/test/BuildClassTest.kt:30]: @geoff-powell you used the built-in `assert` here instead of `assertEquals`, as far as I know this depends on `-ea`, so these might be not executed all the time giving a false positive test success. Was this intentional?
