### PR TITLE
Setup max percent difference as a parameter

### LINKED ISSUE #188: Max percent difference causes false positives
**Environment:**
- Paparazzi: 0.6.0
- Android API: less than 30 (e.g.: 29)
- OpenJDK: 11.0.9
- Mac OS: 10.15.6

**Description:**

The `MAX_PERCENT_DIFFERENCE` value may be too high (currently `0.1`) and small changes in big snapshots (like a lighter `textColor`) don't fail the test. 

Also, this constant could be a parameter of the Paparazzi configuration, falling back to the current value as default:

```
@get:Rule
internal var paparazzi = Paparazzi(maxPercentDifference = 0.01)
```

**Steps:**

1. **Given the golden image**
ca skipthedishes customer ui_MenuItemOptionRadioGroupComponentTests_screenshot_ThemeOrange_idle

2. **And the new change**

ca skipthedishes customer ui_MenuItemOptionRadioGroupComponentTests_screenshot_ThemeOrange_idle

3. With `MAX_PERCENT_DIFFERENCE = 0.1` the test still pass

4. With `MAX_PERCENT_DIFFERENCE = 0.01` the test fails with the expected delta

delta-ca skipthedishes customer ui_MenuItemOptionRadioGroupComponentTests_screenshot_ThemeOrange_idle

### PR DESCRIPTION
**Pull request by omainegra**
Replace `MAX_PERCENT_DIFFERENCE` constant with `maxPercentDifference` parameter.

Fixes #188

### CODE REVIEW

File: paparazzi/src/main/java/app/cash/paparazzi/internal/ImageUtils.kt [hunk 1]
```diff
@@ -63,7 +61,8 @@ internal object ImageUtils {
   @Throws(IOException::class)
   fun requireSimilar(
     relativePath: String,
-    image: BufferedImage
+    image: BufferedImage,
+    maxPercentDifferent: Double
```
Comment (jrodbx) [inline paparazzi/src/main/java/app/cash/paparazzi/internal/ImageUtils.kt:65]:
```suggestion
    maxPercentDifference: Double
```

File: paparazzi/src/main/java/app/cash/paparazzi/internal/ImageUtils.kt [hunk 2]
```diff
@@ -87,7 +86,7 @@ internal object ImageUtils {
             relativePath,
             goldenImage,
             thumbnail,
-            MAX_PERCENT_DIFFERENCE
+            maxPercentDifferent
```
Comment (jrodbx) [inline paparazzi/src/main/java/app/cash/paparazzi/internal/ImageUtils.kt:89]:
```suggestion
            maxPercentDifference
```

**Review by jrodbx — APPROVED** [review]
