### PR TITLE
Make the `PaparazziPlugin` compatible with Gradle Isolated Projects

### LINKED ISSUE #1859: Support Isolated Projects
[Isolated Projects](https://docs.gradle.org/current/userguide/isolated_projects.html)

Project cannot compile due to this error:

```
org.gradle.api.InvalidUserCodeException: Project ':some-project' cannot dynamically look up a property in the parent project ':'
	at org.gradle.api.internal.project.DefaultProject.getProperties(DefaultProject.java:1231)
	at app.cash.paparazzi.gradle.PaparazziPlugin$setupPaparazzi$1.invoke$lambda$38(PaparazziPlugin.kt:215)
	at app.cash.paparazzi.gradle.PaparazziPlugin$setupPaparazzi$1.invoke$lambda$39(PaparazziPlugin.kt:198)
```

my guess is with this line:
```kotlin
test.systemProperties.putAll(project.properties.filterKeys { it.startsWith("app.cash.paparazzi") })
```

### PR DESCRIPTION
**Pull request by SimonMarquis**
by replacing global access to `project.properties` with the more efficient `project.providers.gradlePropertiesPrefixedBy`.

Closes #1859

### CODE REVIEW

File: paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt [hunk 1]
```diff
@@ -223,7 +223,7 @@ public class PaparazziPlugin @Inject constructor(
         test.systemProperties["paparazzi.report.dir"] = reportOutputDir.get().toString()
         test.systemProperties["paparazzi.snapshot.dir"] = snapshotOutputDir.toString()
         test.systemProperties["paparazzi.artifacts.cache.dir"] = gradleUserHomeDir.path
-        test.systemProperties.putAll(project.properties.filterKeys { it.startsWith("app.cash.paparazzi") })
+        test.systemProperties.putAll(project.providers.gradlePropertiesPrefixedBy("app.cash.paparazzi").get())
```
Comment (SimonMarquis) [inline paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt:226]: This is not a 1:1 replacement as `project.properties` aggregates many sources, but I don't think it is currently used in this way.

**Comment by matejdro** [comment]
Any chance of a release with this included?

**Comment by geoff-powell** [comment]
> Any chance of a release with this included?

Yes, this should be released in 2.0.0-alpha03 soon
